/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package templarCoin.gui;

import blockChain.p2p.miner.InterfaceRemoteMiner;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import CarsOnBlocks.utils.RMI;
import templarCoin.core.User;


/**
 *
 * @author aulas
 */
public class Autentication extends javax.swing.JFrame {

    /**
     * Creates new form Autentication
     */
    public Autentication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tpMain = new javax.swing.JTabbedPane();
        pnLogin = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        txtRemote = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtRegisterUser = new javax.swing.JTextField();
        txtRegisterPass1 = new javax.swing.JPasswordField();
        btRegister = new javax.swing.JButton();
        txtRegisterPass2 = new javax.swing.JPasswordField();
        spList = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tpMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpMainStateChanged(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtUser.setText("manso");
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User Name"));

        txtPassword.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtPassword.setToolTipText("");
        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/login_2.png"))); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        txtRemote.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRemote.setText("//10.10.192.132:10010/miner");
        txtRemote.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Server"));

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRemote, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUser))
                .addContainerGap())
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtRemote, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tpMain.addTab("Login", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/login.png")), pnLogin); // NOI18N

        txtRegisterUser.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User Name"));

        txtRegisterPass1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterPass1.setToolTipText("");
        txtRegisterPass1.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        btRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/register_2.png"))); // NOI18N
        btRegister.setText("Register");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        txtRegisterPass2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtRegisterPass2.setToolTipText("");
        txtRegisterPass2.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(txtRegisterUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegisterPass1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtRegisterPass2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(txtRegisterPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(txtRegisterPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        tpMain.addTab("Register", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/register.png")), jPanel4); // NOI18N

        list.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        spList.setViewportView(list);

        tpMain.addTab("Users", new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/user.png")), spList); // NOI18N

        jPanel1.add(tpMain, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/templarCoin/multimedia/templarCoin_2.png"))); // NOI18N
        jLabel1.setText("Templar Coin");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed

        try {
            User u = User.load(txtRegisterUser.getText());
            JOptionPane.showMessageDialog(this, "As passwords não combinam");
            return;
        } catch (Exception e) {
        }
        try {
            if (!Arrays.equals(txtRegisterPass1.getPassword(), txtRegisterPass2.getPassword())) {
                return;
            }
            User.register(txtRegisterUser.getText(), new String(txtRegisterPass1.getPassword()), "Client");
            JOptionPane.showMessageDialog(this, "User registado");

        } catch (Exception ex) {
            Logger.getLogger(Autentication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    private void tpMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpMainStateChanged
        if (tpMain.getSelectedComponent() == spList) {
            DefaultListModel model = new DefaultListModel();
            model.addAll(User.getUserList());
            list.setModel(model);
        }
    }//GEN-LAST:event_tpMainStateChanged

    private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
        if (list.getSelectedIndex() >= 0) {
            User u = (User) list.getSelectedValues()[0];
            txtUser.setText(u.getName());
            txtPassword.requestFocus();
            tpMain.setSelectedComponent(pnLogin);
        }
    }//GEN-LAST:event_listValueChanged

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        try {
            User user = User.load(txtUser.getText(), new String(txtPassword.getPassword()));
            InterfaceRemoteMiner miner= ( InterfaceRemoteMiner)
                    RMI.getRemote(txtRemote.getText());
            user.setMiner(miner);
            this.dispose();
            new TemplarCoinGUI(user).setVisible(true);
//            new SecureFiles(user).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Autentication.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autentication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JList<String> list;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JScrollPane spList;
    private javax.swing.JTabbedPane tpMain;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRegisterPass1;
    private javax.swing.JPasswordField txtRegisterPass2;
    private javax.swing.JTextField txtRegisterUser;
    private javax.swing.JTextField txtRemote;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
